#!/bin/bash

set -eo pipefail

if [ -z "$GIT_USER" ]
then
  GIT_USER="deploy-bot"
fi

if [ -z "$GIT_EMAIL" ]
then
  GIT_EMAIL="deploy-bot@github.com"
fi

if [ -z "$BRANCH" ]
then
  BRANCH="main"
fi

if [ -z "$COMMIT_DIR" ]
then
  COMMIT_DIR="./"
fi

COMMIT_FILE="auto_commited"

DATETIME=(date +%Y%d%m%H%M%S)
echo "$DATETIME" >> "$COMMIT_DIR$COMMIT_FILE"

git config user.name "$GIT_EMAIL"
git config user.email "$GIT_EMAIL"

git add  "$COMMIT_DIR$COMMIT_FILE"
git commit -m "Auto commit generated by $GIT_USER at $DATETIME"
git push
