name: Repo Toucher

# Run every hour
on:
  push
#  schedule:
#    - cron: "* * * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    defaults:
      run:
        working-directory: repo-toucher
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        run: ./commit.sh
        env:
          BRANCH: master


