name: Touch auto_commited
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Update commit file
        run: date +%Y%m%s%H%M%S > auto_commited
      - name: Commit report
        run: |
          git config --global user.name 'Deploy Bot'
          git config --global user.email 'deploy-bot@users.noreply.github.com'
          git add auto_commited
          git commit -m "Automated report"
          git push
